from typing import Protocol

class BrokerAPI(Protocol):
    def get_price(self, symbol: str) -> str: ...
    def get_profile(self, symbol: str) -> str: ...
    def get_history(self, symbol: str, period: str = "1mo", interval: str = "1d") -> str: ...
    def get_fundamentals(self, symbol: str) -> str: ...
    def get_financials(self, symbol: str) -> str: ...
    def get_ratios(self, symbol: str) -> str: ...
    def get_recommendations(self, symbol: str) -> str: ...
    def get_news(self, symbol: str, num_stories: int = 3) -> str: ...
    def get_indicators(self, symbol: str, period: str = "3mo") -> str: ...
