from typing import Optional, Any
from pydantic import BaseModel

class CompanyInfo(BaseModel):
    Name: Optional[str]
    Symbol: Optional[str]
    CurrentStockPrice: Optional[str]
    MarketCap: Optional[str]
    Sector: Optional[str]
    Industry: Optional[str]
    Address: Optional[str]
    City: Optional[str]
    State: Optional[str]
    Zip: Optional[str]
    Country: Optional[str]
    EPS: Optional[float]
    PERatio: Optional[float]
    WeekLow52: Optional[float]
    WeekHigh52: Optional[float]
    DayAverage50: Optional[float]
    DayAverage200: Optional[float]
    Website: Optional[str]
    Summary: Optional[str]
    AnalystRecommendation: Optional[str]
    NumberOfAnalystOpinions: Optional[int]
    Employees: Optional[int]
    TotalCash: Optional[float]
    FreeCashflow: Optional[float]
    OperatingCashflow: Optional[float]
    EBITDA: Optional[float]
    RevenueGrowth: Optional[float]
    GrossMargins: Optional[float]
    EbitdaMargins: Optional[float]

class Fundamentals(BaseModel):
    symbol: str
    company_name: Optional[str]
    sector: Optional[str]
    industry: Optional[str]
    market_cap: Optional[Any]
    pe_ratio: Optional[Any]
    pb_ratio: Optional[Any]
    dividend_yield: Optional[Any]
    eps: Optional[Any]
    beta: Optional[Any]
    week_high_52: Optional[Any]
    week_low_52: Optional[Any]